### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JacondaMarsi** [lntechnical2/PyYouTube#12]
Traceback (most recent call last):
  File "E:/Youtube_info/get_info.py", line 6, in <module>
    data = Data("https://youtu.be/"+line.strip()).data()
  File "C:\Python37\lib\site-packages\py_youtube\pyyoutube.py", line 247, in data
    "duration":duration,
NameError: name 'duration' is not defined

**Comment by ghost** [comment]
bug still not fixed

**Comment by ghost** [comment]
tried to remove that line; the code finishes to work but it outputs bad results: no like/dislike information
```
{'id': 'HhHzCfrqsoE', 'title': 'How To Create MongoDB Database  Url', 'thumbnails': 'https://i.ytimg.com/vi/HhHzCfrqsoE/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==\\u0026rs=AOn4CLBOkJZAdEpYxQOVdaUxFHdbThH_DQ', 'views': '2347', 'likes': None, 'dislikes': None, 'publishdate': '2021-08-04', 'category': 'Howto \\u0026 Style', 'channel_name': 'Ln Technical', 'subscriber': '2.940 iscritti', 'keywords': 'video, condivisione, telefono con videocamera, videotelefono, gratuito, caricare'}
```

tested with this random video: https://www.youtube.com/watch?v=HhHzCfrqsoE

**Comment by lntechnical2** [comment]
> bug still not fixed

We Need To Make Upadate

**Comment by lntechnical2** [comment]
Fixed Now
